#!/bin/bash
#MISE description="Validate workflows.yaml against schema"
set -eo pipefail

cd "$(git rev-parse --show-toplevel)"

check-jsonschema --schemafile workflows.schema.json workflows.yaml
echo "workflows.yaml is valid"
